# Common costmap parameters for real robot

# 障碍物层配置
obstacle_range: 2.5
raytrace_range: 3.0

# 机器人足迹
footprint: [[-0.3, -0.2], [-0.3, 0.2], [0.3, 0.2], [0.3, -0.2]]

# 充气半径
inflation_radius: 0.5
cost_scaling_factor: 10.0

# 传感器数据
observation_sources: laser_scan_sensor

laser_scan_sensor:
  sensor_frame: laser_link
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true
  expected_update_rate: 0.0
  observation_persistence: 0.0
  inf_is_valid: true
  clear_on_initial_publish: true
